### ISSUE TITLE
The program isn't working, or the instruction manual isn't clear enough

### ISSUE THREAD

**Issue by Ragnay** [approved/OddAutoWalker#10]
Hi hope you doing well, i was testing your program and I'm not sure if I'm missing something or it doesn't work anymore. When i launch it and am in game, when I press 'C' the program just make me spam my right click in fact, so it doesnt orbwalk at all and act like a right click macro. I checked the code and i get what it does but maybe someting has change for lol that makes the program unable to find some datas. Thanks for reading I stay up for more conversation about this, have a great day ;)

**Comment by carloskpo12** [comment]
igualmente

**Comment by approved** [comment]
I've stated previously that I do not intend on adding champion specific targeting. It's out of the scope I want to provide and would be difficult to implement in a sane way. Currently the program is more like a right click macro, as you said, but it uses the in-game timings to decide when to click.

**Comment by byGits** [comment]
I understand this isn't champion-specific, but it does not even do Auto-attacks, I've set "Play Attack Move" to "A" but still all it does is right click, attacking nothing, so it isn't actually "OrbWalker" (no auto attacking), just spamming right clicks.

Thanks so much for the efforts, but I hope you'll fix it to work again, as I intend to experiment with it for a project, not playing etc.

**Comment by byGits** [comment]
> I've stated previously that I do not intend on adding champion specific targeting. It's out of the scope I want to provide and would be difficult to implement in a sane way. Currently the program is more like a right click macro, as you said, but it uses the in-game timings to decide when to click.

I understand this isn't champion-specific, but it does not even do Auto-attacks, I've set "Play Attack Move" to "A" but still all it does is right click, attacking nothing, so it isn't actually "OrbWalker" (no auto attacking), just spamming right clicks.

Thanks so much for the efforts, but I hope you'll fix it to work again, as I intend to experiment with it for a project, not playing etc.
