### ISSUE TITLE
new update from lol make script unusable

### ISSUE THREAD

**Issue by TueurDeBrioche** [approved/OddAutoWalker#14]

**Comment by TueurDeBrioche** [comment]
auto attack are always cancel orbwalker is not working

**Comment by ThauMish** [comment]
ho that's why...

**Comment by approved** [comment]
This was an issue on Riot's end and should have been fixed yesterday.

See their Twitter: [Bug Fix announcement](https://twitter.com/LoLDev/status/1623916453941624832)
