### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by krukuhehe** [approved/OddAutoWalker#7]
- Changable Key
- Attack Only Champion 
- If possible, lane clear and last hit

🥇

**Comment by SanderJH** [comment]
yeah, we need a attack only champion

**Comment by lolzake** [comment]
we really need attack champions only

**Comment by approved** [comment]
This tool has no intention of supporting attack champions only. That feature would require either pixel screen reading, or reading from memory.

This is also true of lane clear/last hit.

Neither of those features will be implemented at the current time, and there is no intention of ever supporting them. 

However, you can see issue #8 for ongoing development in to the key bind request.
