### ISSUE TITLE
Add support for custom active key key bind

### ISSUE THREAD

**Issue by approved** [approved/OddAutoWalker#8]
This should allow users to use whichever key bind they desire, rather than hard coding it to 'C'.

**Comment by lolzake** [comment]
does this mean we can use attack champions only?

**Comment by lolzake** [comment]
the hotkey

**Comment by approved** [comment]
This was specifically to address not being able to change which key was used to activate the orb walker. If you checked why issue #7 was closed, you would see that I said I have no intentions of currently supporting attacking champions only.
